### PR TITLE
Develop: youtube search feature

### PR DESCRIPTION
**Pull request by cronix1000**
This is the second pull request can you please see if the code lines up?

I did a pull upstream and it said its all caught up

### CODE REVIEW

**Comment by Paulmski** [comment]
As it stands I don't think this feature is ready for the develop branch. I really like the idea though so I'll create a fork off of the develop branch so it can be worked on.

I think it would be ideal if the results were always related to programming or coding in some way.


Here is the error I received when using multiple keywords:
'Ignoring exception in command search:
Traceback (most recent call last):
  File "/home/paulmolczanski/Documents/github/Discord-Bot/Discord-Bot_env/lib/python3.10/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/paulmolczanski/Documents/github/Discord-Bot/src/__main__.py", line 218, in search
    html = urllib.request.urlopen("https://www.youtube.com/results?search_query={}".format(arg))
  File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib64/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1287, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib64/python3.10/http/client.py", line 1121, in putrequest
    self._validate_path(url)
  File "/usr/lib64/python3.10/http/client.py", line 1221, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/results?search_query=ruby on rails' (found at least ' ')'

**Comment by Paulmski** [comment]
Also just to make it easier mention the issue that you are working on in the pull request. I'll help out with this too, thanks for the help!

**Comment by cronix1000** [comment]
what are you doing when searching for multiple words because im not getting
any errors

**Comment by tuanyvan** [comment]
> what are you doing when searching for multiple words because im not getting any errors

I think this bug was before you submitted your fix (#57) based on the InvalidURL error in @Paulmski's post. It should be fixed now with your recent commit.

**Pull request merged**
